SELECT * FROM [computer_std].[dbo].[dim_location];
SELECT * FROM [computer_std].[dbo].[dim_priority];
SELECT * FROM [computer_std].[dbo].[dim_payment];
SELECT * FROM [computer_std].[dbo].[dim_store];
SELECT * FROM [computer_std].[dbo].[dim_date];
SELECT * FROM [computer_std].[dbo].[dim_customer];
SELECT * FROM [computer_std].[dbo].[dim_pc_spec];
SELECT * FROM [computer_std].[dbo].[dim_channel];
SELECT * FROM [computer_std].[dbo].[Fact_pc_sales];